title: Speed matters
description: A blog about writing fast Python code
show_downloads: true

baseurl: /
url: "https://brmmm3.github.io"

google_analytics:

blog:
  date_format: "%-d %b %Y"

theme: jekyll-theme-cayman

