# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: An occasional blog on Python programming
email: mrbm74@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Is it possible to write fast programs in Python? Yes it is, if you do it the right way.
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  brmmm3

# Build settings
markdown: kramdown

theme:
